#!/usr/bin/env sh

set -e
set -x

host="internal2.innoq.com"

ssh $host 'rm ~/tmp/mittach-*.tar.gz'
scp dist/mittach-*.tar.gz $host:~/tmp/
ssh $host 'cd /var/www/internal.innoq.com/mittach/ && ' \
		'. venv/bin/activate && ' \
		'pip install -U $HOME/tmp/mittach-*.tar.gz && ' \
		'sudo -S apache2ctl restart'
