#!/usr/bin/env python

"""
launch development server

Usage:
  $ ./server [development|testing|production]
"""

import sys
import os


def main(args):
    from mittach.web import app
    print "[INFO] starting in %s mode" % app.config["MODE"]
    app.run()

    return True


if __name__ == "__main__":
    status = not main(sys.argv)
    sys.exit(status)
